module.exports.createUser = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.verifyUser = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.createProduct = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.fetchProducts = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.updateProduct = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.deleteProduct = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.updateCart = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.fetchCart = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.createOrder = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.fetchOrders = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.fetchSessions = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}

module.exports.processPayment = async (req, res) => {
    try {

    }
    catch (error) {
        return res.status(500).json({ error })
    }
}